### ISSUE TITLE
PlexSet Analysis

### ISSUE THREAD

**Issue by yanwu2014** [mcanouil/NACHO#30]
Hey guys,

This looks like an awesome tool! I was wondering if NACHO supported PlexSet analysis where each well/lane is multiplexed with up to 8 samples? If so, it looks like the `load_rcc` function requires each sample to be a separate file so should we demultiplex each well/lane?

Thanks in advance for your help!
Yan

**Comment by mcanouil** [comment]
Hi,

Unless NanoString made a major update of their RCC file format, multiplex data are the same as regular data.
The difference is instead of having "Endogenous", you have "Endogenous1", ..., "Endogenous8" for multiplex, which is parsed and read by NACHO.

For short, it worked before, thus should work now.
If not, please fill an issue with a reproducible example (fake RCC file close to yours for example)
