### ISSUE TITLE
Is it possible to upload a sample sheet using the NACHO shiny app?

### ISSUE THREAD

**Issue by apeleraux** [mcanouil/NACHO#35]
This would enable to customize the plots, for example coloring by group, treatment, timepoint, etc rather than cartridgeID.

**Comment by mcanouil** [comment]
This is a good idea to complete a posteriori the dataset with outside information.

I'll try to have a look at the best way to do that from both shiny and command line.

Feel free (to try) to make a PR, if you feel up to it.

**Comment by apeleraux** [comment]
Thanks for your rapid answer. I may not have much time to develop this functionality, but I will for sure be willing to test it if you implement it.

**Comment by mcanouil** [comment]
Hi,

I added the possibly to include a CSV file along with the RCC files in the shiny app.
`IDFILE` must be in this CSV file and contains the RCC filenames.
Additionally, if using a multiplexed NanoString array, `plexset_id` (S1, S2, ..., S8) must also be provided.

This allows to the "gear" menu in each plots to colour points based on any technical variables or any variables from the provided CSV file.

It is already available in the development version `remotes::install_github("mcanouil/NACHO")`.
Be aware that this version might not work in your current workflow, since it is now using `data.table` instead of several `tidyverse`packags.
